### ISSUE TITLE
Add Jest Mock for RNCallKeep

### ISSUE THREAD

**Issue by jpotts18** [react-native-webrtc/react-native-callkeep#369]
## Problem

* I need to be able to use RN-callkeep without a native device being required. 

```
Invariant Violation: Native module cannot be null.

  at invariant (node_modules/invariant/invariant.js:40:15)
  at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:36:7)
  at Object.<anonymous> (node_modules/react-native-callkeep/actions.js:4:22)
  at Object.<anonymous> (node_modules/react-native-callkeep/index.js:3:1)\
```

## Proposal

I would like to add a jest mock similar to how these libraries have implemented `jest/` folders for easy import

* [react-native-netinfo](https://github.com/react-native-netinfo/react-native-netinfo/blob/master/jest/netinfo-mock.js)
* [react-native-async-storage](https://github.com/react-native-async-storage/async-storage/blob/master/jest/async-storage-mock.js)
* [react-native-device-info](https://github.com/react-native-device-info/react-native-device-info/blob/master/jest/react-native-device-info-mock.js)

#### Methods to mock

* addEventListener - 

## Approach

- [ ] Mock the external interface of 
- [ ] Update readme to notify about how to test
- [ ] 

## Notes

**Comment by eduduardo** [comment]
This should resolve:
```
jest.mock('react-native-callkeep/actions', () => {
  return {
    eventEmitter: jest.fn(),
  };
});
```
