### ISSUE TITLE
RNCallKeep.displayIncomingCall() is not working for Android 11

### ISSUE THREAD

**Issue by usamaabutt** [react-native-webrtc/react-native-callkeep#441]
Hello guys,

I am using `react-native-callkeep` lib for a calling app and it’s working fine in iOS but in Android it’s not working

`RNCallKeep.displayIncomingCall(callUUID, '', callerName)`

Doesn’t works for android.
Any help will be appreciated, Thanks!

**Comment by namnm** [comment]
@usamaabutt Can you provide more information? Have you tested by just directly calling `displayIncomingCall` without any of your app logic?

**Comment by men3malgmatti** [comment]
I have the same issue, did you manage to solve it ?

**Comment by men3malgmatti** [comment]
Btw just using yarn android did for me

**Comment by rajasekhar911** [comment]
Fixed this issue by going to Phone App (Call App) -> Settings -> Call Settings -> All Calling Accounts -> Enable for the app.
This was in development mode.

**Comment by Shivaniaddval** [comment]
I am also using react-native-callkeep lib for a calling app and it’s working fine in iOS but in Android it’s not working

On calling this ->

**RNCallKeep.displayIncomingCall(uid, handle, localizedCallerName = '', handleType = 'number', hasVideo = false, options = null);**

I am getting following error:

` com.facebook.react.bridge.ObjectAlreadyConsumedException: Map already consumed
        at com.facebook.react.bridge.WritableNativeMap.putString(Native Method)
        at io.wazo.callkeep.RNCallKeepModule$VoiceBroadcastReceiver.onReceive(RNCallKeepModule.java:1148)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)`

Thank you in advance for your assistance!

**Comment by KolissnikBogdan** [comment]
@shivi126 Hi, did you manage to solve this problem?
