### ISSUE TITLE
System does not support feature android.software.connectionservice

### ISSUE THREAD

**Issue by giangntr** [react-native-webrtc/react-native-callkeep#491]
# Bug report

## Description
App crash on Android 6.0, 7.1.1 and 7.1.2

This is my Manifest

```
        <service
            android:name="io.wazo.callkeep.VoiceConnectionService"
            android:foregroundServiceType="microphone"
            android:label="Wazo"
            android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE">
            <intent-filter>
                <action android:name="android.telecom.ConnectionService" />
            </intent-filter>
        </service>
```

build.gradle

```
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 23
        compileSdkVersion = 30
        targetSdkVersion = 30
        kotlinVersion = "1.4.32"
        ndkVersion = "20.1.5948944"
    }
```

## Versions
    - Callkeep: 4.1.0
    - React Native: 0.65.1
    - Android: Android 7.1.2
    - Phone model: SM-G973N 

## Logs

```
java.lang.UnsupportedOperationException: System does not support feature android.software.connectionservice
    at android.os.Parcel.readException(Parcel.java:1696)
    at android.os.Parcel.readException(Parcel.java:1637)
    at com.android.internal.telecom.ITelecomService$Stub$Proxy.registerPhoneAccount(ITelecomService.java:937)
    at android.telecom.TelecomManager.registerPhoneAccount(TelecomManager.java:839)
    at io.wazo.callkeep.RNCallKeepModule.registerPhoneAccount(RNCallKeepModule.java:590)
    at io.wazo.callkeep.RNCallKeepModule.registerPhoneAccount(RNCallKeepModule.java:143)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:154)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:761)
```

Is there any wrong with my configuration?

**Comment by sashabty** [comment]
Did you manage to handle this issue? I'm testing my app with nox emulator and run into same problem as well.

**Comment by 2ducanhpham** [comment]
Same problem!

**Comment by wilmxre** [comment]
hey @giangnt1, @sashabty , @2ducanhpham did you manage to fix this issue?

**Comment by ark-fabtechsol** [comment]
For manifest or any other native side issues You should try running the application in native code editor like android studio or xcode. it takes you to the root cause.

Add this below the connection service line
android:exported="true"
