### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MusabBasheer** [react-native-webrtc/react-native-callkeep#608]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [ ] iOS

## Versions
    - Callkeep:
    - React Native:
    - iOS:
    - Android:
    - Phone model: 

## Logs

```
RNCallKeepModule.java line 983
io.wazo.callkeep.RNCallKeepModule.hasPhoneAccount

Fatal Exception: java.lang.SecurityException: Neither user 10394 nor current process has android.permission.READ_PHONE_NUMBERS.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2441)
       at android.os.Parcel.createException(Parcel.java:2425)
       at android.os.Parcel.readException(Parcel.java:2408)
       at android.os.Parcel.readException(Parcel.java:2350)
       at com.android.internal.telecom.ITelecomService$Stub$Proxy.getPhoneAccount(ITelecomService.java:1982)
       at android.telecom.TelecomManager.getPhoneAccount(TelecomManager.java:1391)
       at io.wazo.callkeep.RNCallKeepModule.hasPhoneAccount(RNCallKeepModule.java:983)
       at io.wazo.callkeep.RNCallKeepModule.endAllCalls(RNCallKeepModule.java:391)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:920)
```

**Comment by m4r00p** [comment]
I got the very same issue.

Any clues?

TIA!

**Comment by nero2009** [comment]
Getting this same issue after bumping `targetSdkVersion` to 31

please how did you fix @m4r00p @MusabBasheer

**Comment by nero2009** [comment]
Fixed [here](https://github.com/react-native-webrtc/react-native-callkeep/pull/556)
ugrade to 4.3.3 should fix

**Comment by nero2009** [comment]
Hi @MusabBasheer were you able to fix this issue. upgrading to 4.3.3 didnt fix
