### ISSUE TITLE
Selfmanaged Callkeep crashes after bumpig targetSdkVersion to 31

### ISSUE THREAD

**Issue by nero2009** [react-native-webrtc/react-native-callkeep#635]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android

## Description

React native callkeep is unable to run displayIncomingCall when the app receive a high priority FCM notification and starts the background service that wakes the app up .  Instead it crashes.

Similar issue was reported [here](https://github.com/react-native-webrtc/react-native-callkeep/issues/608) 

please i need to know if you have a self managed setup running on android 12> @linus-komnick @manuquentin 

Android Permissions.
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="com.smarthealthmobile.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.RECORD_VIDEO" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.BIND_TELECOM_CONNECTION_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
    <uses-permission android:name="android.permission.READ_CALL_LOG" tools:node="remove" />
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
    <uses-feature android:name="android.hardware.telephony" android:required="false" />


```

## Versions
    - Callkeep: 4.3.3
    - React Native: 0.63.4
    - Android: Android 12 and above
    - Phone model: Samsung galaxy ultra and google pixel 3a

## Logs

```
2022-11-25 13:50:14.285 5722-5782/com.smarthealthmobile E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.SecurityException: Neither user 10315 nor current process has android.permission.READ_PHONE_NUMBERS.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at com.android.internal.telecom.ITelecomService$Stub$Proxy.getPhoneAccount(ITelecomService.java:1926)
        at android.telecom.TelecomManager.getPhoneAccount(TelecomManager.java:1374)
        at io.wazo.callkeep.RNCallKeepModule.hasPhoneAccount(RNCallKeepModule.java:681)
        at io.wazo.callkeep.RNCallKeepModule.displayIncomingCall(RNCallKeepModule.java:182)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:1012)

```

**Comment by sboily** [comment]
This message indicate you missed permission.

    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />

**Comment by nero2009** [comment]
https://github.com/react-native-webrtc/react-native-callkeep/issues/635#issuecomment-1327474596

> This message indicate you missed permission.
> 
> ```
> <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
> ```

Adding this permission doesn't fix it

**Comment by nero2009** [comment]
Please reopen issue

**Comment by sboily** [comment]
What is the message? We are using this library with self managed and we don't have this issue. So you probably missed something in your permission.

**Comment by nero2009** [comment]
These are my permissions on the app:

```
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="com.smarthealthmobile.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.RECORD_VIDEO" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.BIND_TELECOM_CONNECTION_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
    <uses-permission android:name="android.permission.READ_CALL_LOG" tools:node="remove" />
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
    <uses-feature android:name="android.hardware.telephony" android:required="false" />
```

Do I have to require any of these permissions at runtime?

**Comment by nero2009** [comment]
Requesting for `READ_PHONE_NUMBERS ` permission at runtime fixes this issue. Defining this permission in the android manifest is not enough. You have to request for it

` const granted = await PermissionsAndroid.request('android.permission.READ_PHONE_NUMBERS')`

**Comment by Betoxx1** [comment]
When i try to apply `const granted = await PermissionsAndroid.request('android.permission.READ_PHONE_NUMBERS')`  I receive this error in vsCode:  Argument of type '"android.permission.READ_PHONE_NUMBERS"' is not assignable to parameter of type 'Permission'.

and I keep receiving this in the log:
  java.lang.SecurityException: Neither user 10315 nor current process has android.permission.READ_PHONE_NUMBERS.

**Comment by nero2009** [comment]
1.  READ_PHONE_NUMBERS is not yet define as a type for PermissionsAndroid on react native yet
2. You should request this permission ```const granted = await PermissionsAndroid.request('android.permission.READ_PHONE_NUMBERS')``` before you receive or make a call with react native callkeep

**Comment by dfbg-eldertech** [comment]
When I request the READ_PHONE_NUMBERS permission my app cannot be found in the play store on devices without telecommunication feature (like tablets). Any idea how to handle this?
