### ISSUE TITLE
Caused by java.lang.NoSuchMethodError: No virtual method stopForeground on Android 6

### ISSUE THREAD

**Issue by alpha2048** [react-native-webrtc/react-native-callkeep#744]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description

According to Crashlytics, This crash is occurring on Android 6.

`stopForeground` requires Android7 or higher.

## Steps to Reproduce

1. receive a call in background on Android 6.
2. end the call via `reportEndCallWithUUID`

## Versions
    - Callkeep: 4.3.9
    - React Native: 0.69.12
    - iOS:
    - Android: 6
    - Phone model: 

## Logs

```
Caused by java.lang.NoSuchMethodError: No virtual method stopForeground(I)V in class Lio/wazo/callkeep/VoiceConnectionService; or its super classes (declaration of 'io.wazo.callkeep.VoiceConnectionService' appears in xxx.apk)
       at io.wazo.callkeep.VoiceConnectionService.stopForegroundService(VoiceConnectionService.java:356)
       at io.wazo.callkeep.VoiceConnectionService.deinitConnection(VoiceConnectionService.java:159)
       at io.wazo.callkeep.VoiceConnection.reportDisconnect(VoiceConnection.java:167)
       at io.wazo.callkeep.RNCallKeepModule.reportEndCallWithUUID(RNCallKeepModule.java:582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:207)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by ramijarrar** [comment]
Did you set `foregroundServiceType` to "phoneCall" as per the [instructions](https://github.com/react-native-webrtc/react-native-callkeep/blob/master/docs/android-installation.md)?

**Comment by alpha2048** [comment]
I already set this, ss something wrong?
`android:foregroundServiceType="camera|microphone|phoneCall"`

**Comment by ramijarrar** [comment]
The problem is this [line](https://github.com/react-native-webrtc/react-native-callkeep/blob/cc308ce2ed33bcc12ef1ef95468f4a81de7d6d4e/android/src/main/java/io/wazo/callkeep/VoiceConnectionService.java#L362) which should be using the legacy [stopForeground(boolean)](https://developer.android.com/reference/android/app/Service#stopForeground(boolean)) method on Android 6 to maintain backwards compatibility.

I have an existing PR react-native-webrtc#742 to fix the current implementation (which is incorrect even for latest Android).

I could amend it to also support the legacy API, but there are other issues you may run into with really old Android versions (e.g. `checkIsInManagedCall` [requires](https://github.com/react-native-webrtc/react-native-callkeep/blob/cc308ce2ed33bcc12ef1ef95468f4a81de7d6d4e/android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java#L330) Android 8+).

**Comment by alpha2048** [comment]
I think only add `Build.VERSION.SDK_INT >= Build.VERSION_CODES.N` condition like [flutter callkeep](https://github.com/flutter-webrtc/callkeep/blob/50e75bac23b38ac57f8f37eac553297dcfd3453f/android/src/main/java/io/wazo/callkeep/VoiceConnectionService.java#L152C13-L152C59).


[according to this line](https://github.com/react-native-webrtc/react-native-callkeep/blob/cc308ce2ed33bcc12ef1ef95468f4a81de7d6d4e/android/src/main/java/io/wazo/callkeep/VoiceConnectionService.java#L296), Android 7 or below don't support Foreground Service.
